version: '3.4'

services:
  jest_api_tests:
    image: api-node-axios-jest
    container_name: api-tests-jest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    volumes: 
      - ./reports/:/app/reports
